### PR TITLE
Added custom message option

### PR DESCRIPTION
**Pull request by pepsivontwist**
Closes https://github.com/abhisekp/yup-phone/issues/265

### CODE REVIEW

**Comment by abhisekp** [comment]
Please remove all the `dist/` related modifications. It will be auto added when there is version update.

**Comment by abhisekp** [comment]
And please do not update the version.

**Comment by abhisekp** [comment]
And use git rebase and squash your commits to one.

**Comment by abhisekp** [comment]
Thanks for adding this improvement. :smiley:

**Comment by rzmz** [comment]
Is this going to be fixed/merged soon? What can I do to help?

**Comment by abhisekp** [comment]
This is closed in #297

**Comment by abhisekp** [comment]
# Released in npm in `v1.2.0`

**Pull request closed without merging**
